In [7]:
import numpy as np
import torch
from mini_torch.tensor import Tensor as T

In [5]:
a = T.from_numpy('a', np.array([1, 1]).astype(float))
b = T.from_numpy('b', np.array([2, 2]).astype(float))
x = T.from_numpy('x', np.array([3, 3]).astype(float), required_grad=False)
t = T.from_numpy('t', np.array([2, 2]).astype(float), required_grad=False)

In [6]:
print(a)
print(b)
print(x)
print(t)

<class 'mini_torch.tensor.Tensor'>
[1. 1.]
shape: (2,)

<class 'mini_torch.tensor.Tensor'>
[2. 2.]
shape: (2,)

<class 'mini_torch.tensor.Tensor'>
[3. 3.]
shape: (2,)

<class 'mini_torch.tensor.Tensor'>
[2. 2.]
shape: (2,)



In [7]:
y = a**2*x - b/t

In [10]:
y.data

array([2., 2.])

In [8]:
y.backward()

In [11]:
print(a.grad)
print(b.grad)

{'a': array([6., 6.])}
{'b': array([-0.5, -0.5])}


In [12]:
y.zero_grad()

In [13]:
print(a.grad)
print(b.grad)

{'a': 1.0}
{'b': 1.0}


In [26]:
aa = torch.tensor([1.], requires_grad=True)
bb = torch.tensor([2.], requires_grad=True)
xx = torch.tensor([3])
tt = torch.tensor([2])

In [27]:
yy = aa**2*xx - bb/tt

In [28]:
yy

tensor([2.], grad_fn=<SubBackward0>)

In [29]:
yy.backward()

In [30]:
aa.grad

tensor([6.])

In [31]:
bb.grad

tensor([-0.5000])

In [21]:
aa = torch.tensor([1.], requires_grad=True)
bb = torch.tensor([2.], requires_grad=True)
xx = torch.tensor([3])

In [22]:
yy = aa**2*xx - bb

In [23]:
yy

tensor([1.], grad_fn=<SubBackward0>)

In [24]:
yy.backward()

In [30]:
aa.grad

tensor([6.])