In [1]:
import numpy as np
import torch
from mini_torch.tensor import Tensor as T

In [14]:
w0 = T.from_numpy('w0', np.array([-0.5]).astype(float))
w1 = T.from_numpy('w1', np.array([2.7]).astype(float))
w2 = T.from_numpy('w2', np.array([-0.105]).astype(float))
x1 = T.from_numpy('x1', np.array([1.]).astype(float), required_grad=False)
x2 = T.from_numpy('x2', np.array([0.5]).astype(float), required_grad=False)

In [26]:
y = w0 + w1**2*x1 + w2*x2

In [27]:
y.data

array([6.7375])

In [28]:
y.backward()

In [29]:
print(w0.grad)
print(w1.grad)
print(w2.grad)

{'w0': array([1.])}
{'w1': array([5.4])}
{'w2': array([0.5])}


In [30]:
y.zero_grad()

In [31]:
print(w0.grad)
print(w1.grad)
print(w2.grad)

{'w0': array([1.])}
{'w1': array([5.4])}
{'w2': array([0.5])}


In [33]:
tw0 = torch.tensor([-0.5], requires_grad=True)
tw1 = torch.tensor([2.7], requires_grad=True)
tw2 = torch.tensor([-0.105], requires_grad=True)
tx1 = torch.tensor([1.])
tx2 = torch.tensor([0.5]) 

In [34]:
ty = tw0 + tw1**2*tx1 + tw2*tx2

In [35]:
ty

tensor([6.7375], grad_fn=<AddBackward0>)

In [36]:
ty.backward()

In [37]:
print(tw0.grad)
print(tw1.grad)
print(tw2.grad)

tensor([1.])
tensor([5.4000])
tensor([0.5000])
