In [7]:
import numpy as np
import torch
from mini_torch.tensor import Tensor as T

In [2]:
a = T.from_numpy('a', np.array([1]).astype(float))
b = T.from_numpy('b', np.array([2]).astype(float))
x = T.from_numpy('x', np.array([3]).astype(float), required_grad=False)

In [3]:
print(a)
print(b)
print(x)

<class 'mini_torch.tensor.Tensor'>
[1.]
shape: (1,)

<class 'mini_torch.tensor.Tensor'>
[2.]
shape: (1,)

<class 'mini_torch.tensor.Tensor'>
[3.]
shape: (1,)



In [4]:
y = a**2*x - b

In [5]:
y.backward()

{'a': array([6.]), 'b': -1.0}

In [6]:
y.data

array([1.])

In [21]:
aa = torch.tensor([1.], requires_grad=True)
bb = torch.tensor([2.], requires_grad=True)
xx = torch.tensor([3])

In [22]:
yy = aa**2*xx - bb

In [23]:
yy

tensor([1.], grad_fn=<SubBackward0>)

In [24]:
yy.backward()

In [30]:
aa.grad

tensor([6.])